import { Inter } from "next/font/google";
import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.min.css'
import BootstrapInstall from "@/app/components/bootStrap/BootstrapInstall";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyClasses",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
     <meta name="viewport" content="width=device-width, user-scalable=no" />
     <BootstrapInstall/>
    </head>
      <body className={inter.className}> 
        {children}
        </body>
    </html>
  );
}
