import { Inter } from "next/font/google";
import './globals.css'
import 'bootstrap-icons/font/bootstrap-icons.min.css'
import BootstrapInstall from "./components/bootstrap/BootstrapInstall";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyClasses",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <BootstrapInstall/>
      <body className={inter.className}> 
        {children}
        </body>
    </html>
  );
}
